sonar.projectKey=puj-course_FIS_2610_3513_G6
sonar.organization=puj-course

sonar.sources=unimercs-backend
sonar.exclusions=**/node_modules/**,**/uploads/**,**/*.test.js,**/coverage/**

sonar.javascript.lcov.reportPaths=src/test/coverage/lcov.info

sonar.tests=unimercs-backend
sonar.test.inclusions=**/*.test.js

sonar.sourceEncoding=UTF-8

sonar.branch.name=main
