sonar.projectKey=puj-course_FIS_2610_3513_G6
sonar.organization=puj-course

sonar.projectName=UniMercs
sonar.projectVersion=1.0


sonar.sources=src/test/unit

sonar.exclusions=node_modules/**,dist/**,coverage/**,uploads/**

sonar.javascript.lcov.reportPaths=src/test/coverage/lcov.info

sonar.sourceEncoding=UTF-8
