sonar.projectKey=puj-course_FIS_2610_3513_G6
sonar.organization=puj-course

sonar.sources=src/behavioralPatterns,src/CreationalPatterns,src/structuralPatterns
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js

sonar.javascript.lcov.reportPaths=src/test/coverage/lcov.info

sonar.tests=src/test/unit
sonar.test.inclusions=**/*.test.js

sonar.sourceEncoding=UTF-8
